defaultTown: ""

allowTownFriendlyFireManagement: false;
#default is wooden hoe (290)
quickSelectTool: 290
#log verbose information of each MCTowns command issued
logCommands: false
playersCanJoinMultipleTowns: true
#hostname and port of remote bug report handling server
bugReporting:
  hostname: services.jmhertlein.net
  port: 9001

economy:
  economyEnabled: false
  mayorsCanBuyTerritories: false
  pricePerXZBlock: 0
  minNumPlayersToBuyTerritory: 3

  townFees:
    feesEnabled: false;
    feeAmount: 100
    feeDelay: 1728000
    #gracePeriod: amount of time after town creation that the town doesn't need to pay fees
    #default is one week
    gracePeriod: 12096000

  taxes:
    taxesEnabled: false
    percentagesEnabled: false
    maxTaxAmount: 100
    maxTaxPercent: .3
    #default is 1 day: 24 hours * 60 mins
    taxDelayMins: 1440
#
#
#The currently installed version of MCTowns. Do not change this.
installedVersion: 2.3.1
#Seriously don't change it
#
#
