name: MCTowns
main: net.jmhertlein.mctowns.MCTownsPlugin
version: 2.2.0
depend: [WorldGuard]
softdepend: [Vault]
commands:
    mct:
        description: Base command for plugin-wide config or generic commands
        usage: /mct (addtown | removetown | info | join | list | refuse | cancel | donate)
        aliases:
    town:
        description: base command for all town-based commands
        usage: /town (add | remove | active | list | motd | setmayor | bank | spawn | economy | joinmethod | pvp)
        aliases: to
    territory:
        description: base command for all territory-based commands
        usage: /territory (add | redefine | remove | active | list | flag)
        aliases: te
    plot:
        description: base command for all plot-based commands
        usage: /plot (add | redefine | remove | active | list | sign | info | flag | economy)
        aliases: pl
