groups:
  #normal players can look at things
  default:
    type: resident
    inherits:
    authorized:
      - KEY_EXCHANGE
      - TERMINATE_SESSION
      - GET_TOWN_VIEW
      - GET_TOWN_LIST
      - GET_TERRITORY_VIEW
      - GET_TERRITORY_LIST
      - GET_PLOT_VIEW
      - GET_IDENTITY_LIST
      - GET_META_VIEW
      - GET_PLAYER_LIST
      - GET_VIEW_FOR_PLAYER
      - GET_PLOTS_LIST
  #mayors can modify things that they are the mayor of
  mayor:
    type: mayor
    inherits: default
    authorized:
      - UPDATE_TOWN
      - CREATE_TOWN
      - DELETE_TOWN
      - MODIFY_TOWN_MEMBERSHIP
      - MODIFY_TOWN_ASSISTANTS
      - CREATE_TERRITORY
      - DELETE_TERRITORY
      - MODIFY_TERRITORY_MEMBERSHIP
      - UPDATE_PLOT
      - MODIFY_PLOT_MEMBERSHIP
      - CREATE_PLOT
      - DELETE_PLOT
  #admins can update plugin config and change things they are not mayor of
  admin:
    type: admin
    inherits: mayor
    authorized:
      - UPDATE_CONFIG
      - ADD_IDENTITY
      - DELETE_IDENTITY