economyEnabled: false
mayorsCanBuyTerritories: false
pricePerXZBlock: 0
minNumPlayersToBuyTerritory: 3
allowTownFriendlyFireManagement: false;
#default is wooden hoe (290)
quickSelectTool: 290 
#log verbose information of each MCTowns command issued
logCommands: false
playersCanJoinMultipleTowns: true
#hostname and port of remote bug report handling server
bugReportHostname: services.jmhertlein.net
bugReportPort: 9001
#Port remote admin server will listen for clients on
remoteAdminPort: 3333
#length of encryption keys used for remote admin server
#longer = more secure but slower
#shorter = less secure but faster
#min is 512 (will throw errors if less)
#Recommended max is 2048 (will take too long to decode messages if set higher)
#default is 2048
remoteAdminKeyLength: 2048
#valid values: 128, 192 or 256
remoteAdminSessionKeyLength: 256
