name: MCTowns
main: me.everdras.mctowns.MCTowns
version: 1.1.1
depend: [WorldGuard, Vault]
commands:
    mct:
        description: Base command for plugin-wide config or generic commands
        usage: /mct (addtown | removetown | info | join | list | refuse | cancel)
        aliases:
    town:
        description: base command for all town-based commands
        usage: /town (add | remove | active | list | motd | setmayor | bank | spawn | economy | joinmethod | pvp)
        aliases: to
    territory:
        description: base command for all territory-based commands
        usage: /territory (add | remove | active | list | flag)
        aliases: te
    plot:
        description: base command for all plot-based commands
        usage: /plot (add | remove | active | list | sign | info | flag | economy)
        aliases: pl
